apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: product-db-pvc

spec:
  accessModes:  # only one node can read and write
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi