#version: '3.8'

services:
  order-service:
    build: ./orderservice
    ports:
      - "8081:8081"
  user-service:
    build: ./userservice
    ports:
      - "8082:8082"
  product-service:
    build: ./productservice
    ports:
      - "8083:8083"