#version: '3.8'

services:
  order-service:
    build: ./orderservice
    networks:
      - microservices-network
    depends_on:
      - user-service
    environment:
      - USER_SERVICE_URL=http://user-service:8082
      - PRODUCT_SERVICE_URL=http://product-service:8083
    restart: always
  user-service:
    build: ./userservice
    networks:
      - microservices-network
    restart: always
  product-service:
    build: ./productservice
    networks:
      - microservices-network
    restart: always
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - user-service
      - order-service
      - product-service
networks:
  microservices-network: