#version: '3.8'

services:
  order-service:
    build: ./orderservice
    container_name: order-service
    networks:
      - microservices-network
    depends_on:
      user-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      order-db:
          condition: service_healthy
    environment:
      - USER_SERVICE_URL=http://user-service:8082
      - PRODUCT_SERVICE_URL=http://product-service:8083
      - SPRING_DATABASE_URL=jdbc:mysql://order-db:3306/orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
  user-service:
    build: ./userservice
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/productdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
  product-service:
    build: ./productservice
    container_name: product-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://product-db:3306/productdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - microservices-network
    restart: always
    depends_on:
      product-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - user-service
      - order-service
      - product-service
#  adding database
  product-db:
    container_name: product-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
    ports:
      - "3307:3306"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - product-db-data:/var/lib/mysql

  order-db:
    container_name: order-db
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - order-db-data:/var/lib/mysql

  user-db:
    container_name: user-db
    image: mysql:8
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    networks:
      microservices-network:
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - user-db-data:/var/lib/mysql

networks:
  microservices-network:
volumes:
  product-db-data:
  order-db-data:
  user-db-data: