spring.application.name=userservice
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
server.port=8082

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000