apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: {{ .Values.productService.replicas }}

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: product-service
          image: "{{ .Values.productService.image }}:{{ .Values.productService.tag }}"
          ports:
            - containerPort: {{ .Values.productService.containerPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCT_SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_PASSWORD

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.productService.containerPort }}
            initialDelaySeconds: {{ .Values.productService.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.productService.readinessProbe.periodSeconds }}

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.productService.containerPort }}
            initialDelaySeconds: {{ .Values.productService.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.productService.livenessProbe.periodSeconds }}