apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: {{ .Values.productService.servicePort }}
      targetPort: {{ .Values.productService.containerPort }}