name: Deploy Ecommerce System

on:
  workflow_dispatch:
    inputs:
      skip_terraform:
        description: "Skip Terraform infrastructure creation"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
      ec2_ip:
        description: "Existing EC2 Public IP (required when skip_terraform=true)"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:

      # =========================================
      # Checkout Repository
      # =========================================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # =========================================
      # Configure AWS Credentials
      # =========================================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      # =========================================
      # Setup Terraform
      # =========================================
      - name: Setup Terraform
        if: github.event.inputs.skip_terraform != 'true'
        uses: hashicorp/setup-terraform@v3


      # =========================================
      # Terraform Init
      # =========================================
      - name: Terraform Init
        if: github.event.inputs.skip_terraform != 'true'
        working-directory: terraform
        run: |
          echo "======================================="
          echo "Running Terraform Init"
          echo "======================================="

          terraform init

      # =========================================
      # Terraform Plan
      # =========================================
      - name: Terraform Plan
        if: github.event.inputs.skip_terraform != 'true'
        working-directory: terraform
        run: |
          echo "======================================="
          echo "Running Terraform Plan"
          echo "======================================="

          terraform plan

      # =========================================
      # Terraform Apply
      # =========================================
      - name: Terraform Apply
        if: github.event.inputs.skip_terraform != 'true'
        working-directory: terraform
        run: |
          echo "======================================="
          echo "Creating AWS Infrastructure"
          echo "======================================="

          terraform apply -auto-approve

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # =========================================
      # Build ECR docker images
      # =========================================
      - name: Build and Push User Service
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/user-service:latest \
            ./userservice

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/user-service:latest

      - name: Build and Push Product Service
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/product-service:latest \
            ./productservice

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/product-service:latest

      - name: Build and Push Order Service
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/order-service:latest \
            ./orderservice

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/order-service:latest

      - name: Build and Push API Gateway
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/api-gateway:latest \
            ./api-gateway

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/api-gateway:latest

      # =========================================
      # Fetch EC2 Public IP
      # =========================================
      - name: Fetch EC2 Public IP
        if: github.event.inputs.skip_terraform != 'true'
        working-directory: terraform
        run: |
          echo "======================================="
          echo "Fetching EC2 Public IP"
          echo "======================================="

          EC2_IP=$(terraform output -raw public_ip)

          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

          echo "EC2 Public IP: $EC2_IP"

      - name: Validate Existing EC2 IP
        if: github.event.inputs.skip_terraform == 'true'
        run: |
          if [ -z "${{ github.event.inputs.ec2_ip }}" ]; then
            echo "ERROR: ec2_ip is required when skip_terraform=true"
            exit 1
          fi

      - name: Use Existing EC2
        if: github.event.inputs.skip_terraform == 'true'
        run: |
          echo "EC2_IP=${{ github.event.inputs.ec2_ip }}" >> $GITHUB_ENV

      - name: Show Deployment Target IP
        run: |
          echo "Deploying to: $EC2_IP"
      # =========================================
      # Create SSH Key
      # =========================================
      - name: Create SSH Key
        run: |
          echo "======================================="
          echo "Creating SSH Key"
          echo "======================================="

          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem

          chmod 600 private_key.pem

          echo "SSH Key Created Successfully"

      # =========================================
      # Wait for EC2 Initialization
      # =========================================
      - name: Wait for EC2 Startup
        run: |
          echo "======================================="
          echo "Waiting for EC2 Initialization"
          echo "======================================="

          until ssh \
          -o StrictHostKeyChecking=no \
          -o ConnectTimeout=5 \
          -i private_key.pem \
           ubuntu@$EC2_IP "echo ready" 2>/dev/null
           do
           echo "Waiting for SSH..."
           sleep 10
           done



      # =========================================
      # Deploy Application to EC2
      # =========================================
      - name: Deploy Application
        run: |

          echo "======================================="
          echo "Starting Application Deployment"
          echo "======================================="

          ssh -o StrictHostKeyChecking=no \
              -i private_key.pem \
              ubuntu@$EC2_IP << 'EOF'

            set -e

            echo ""
            echo "======================================="
            echo "Connected to EC2"
            echo "======================================="
          
#          if ! command -v docker >/dev/null 2>&1; then
#            echo "Docker not found. Installing..."
#
#            sudo apt update -y
#            sudo apt install -y docker.io docker-compose git awscli
#
#            sudo systemctl enable docker
#            sudo systemctl start docker
#          fi
          
           echo ""
           echo "Verifying installed tools..."
  
           docker --version
           docker-compose --version
           git --version
           aws --version
  
           echo "All required tools are available"

            # ---------------------------------
            # Navigate to Home Directory
            # ---------------------------------
            echo ""
            echo "Navigating to home directory..."

            cd /home/ubuntu

            # ---------------------------------
            # Clone Repository if Needed
            # ---------------------------------
            echo ""
            echo "Checking project repository..."

            if [ ! -d "ecommerce-microservices" ]; then

              echo "Repository not found"

              echo "Cloning repository..."

              git clone https://github.com/Priyanka99809/ecommerce-microservices.git

              echo "Repository cloned successfully"

            else

              echo "Repository already exists"

            fi

            # ---------------------------------
            # Enter Repository
            # ---------------------------------
            echo ""
            echo "Entering project directory..."

            cd ecommerce-microservices

            # ---------------------------------
            # Pull Latest Code
            # ---------------------------------
            echo ""
            echo "Pulling latest code..."

            git pull origin main

            echo "Repository updated successfully"

            # ---------------------------------
            # Stop Existing Containers
            # ---------------------------------
            echo ""
            echo "Stopping old containers..."

            sudo docker-compose -f docker-compose.yml down || true
          
          
            # Remove unused containers/images/networks
            sudo docker system prune -af
          

            echo "Old containers removed successfully"

            # ---------------------------------
            # Build Docker Containers
            # ---------------------------------
            echo ""
            echo "Logging into ECR..."
            
            echo "Verifying IAM Role..."
  
            aws sts get-caller-identity
          
            aws ecr get-login-password \
            --region us-east-1 \
            | sudo docker login \
            --username AWS \
            --password-stdin 703227779312.dkr.ecr.us-east-1.amazonaws.com

            echo "ECR login successful"
  
            echo ""
            echo "Pulling latest Docker images..."
  
            sudo docker-compose -f docker-compose.yml pull
  
            echo "Latest images downloaded successfully"

            # ---------------------------------
            # Start Docker Containers
            # ---------------------------------
            echo ""
            echo "Starting all microservices..."

            sudo docker-compose -f docker-compose.yml up -d

            echo "Microservices started successfully"

            # ---------------------------------
            # Wait for Containers
            # ---------------------------------
            echo ""
            echo "Waiting for services initialization..."

            sleep 25

            echo "Services initialized successfully"

            # ---------------------------------
            # Display Running Containers
            # ---------------------------------
            echo ""
            echo "======================================="
            echo "RUNNING CONTAINERS"
            echo "======================================="
 
            sudo docker ps

            # ---------------------------------
            # Show Container Logs
            # ---------------------------------
            echo ""
            echo "======================================="
            echo "CONTAINER LOGS"
            echo "======================================="

            sudo docker-compose -f docker-compose.yml logs --tail=30
            echo "Disk Usage After Deploy"
            df -h
  
            echo "Docker Usage After Deploy"
            sudo docker system df
            # ---------------------------------
            # Deployment Completed
            # ---------------------------------
            echo ""
            echo "======================================="
            echo "DEPLOYMENT COMPLETED SUCCESSFULLY"
            echo "======================================="

          EOF